local set = vim.opt

set.nu = true
set.rnu = true
set.cursorline = true
set.autoindent = true
set.smartindent = true
set.tabstop = 4
set.softtabstop = 4
set.shiftwidth = 4
set.expandtab = true
set.smarttab = true
set.so = 5
set.incsearch = true
set.hlsearch = false
set.showmatch = true
set.errorbells = false
set.visualbell = false
set.backup = false
set.writebackup = false
set.swapfile = false
set.fileencoding = "utf-8"
set.wrap = false
set.ignorecase = true
set.smartcase = true
set.undofile = true
set.splitbelow = true
set.splitright = true
set.termguicolors = true
set.clipboard = "unnamedplus"
set.conceallevel = 0
set.showtabline = 2
set.timeoutlen = 1000
set.updatetime = 300

vim.wo.signcolumn = "yes"
